services:
  rent-housing-api:
    container_name: rent-housing-api
    restart: always
    image: node:20.10.0
    ports:
      - 4005:3005
    volumes:
      - ./:/usr/src/rent-housing
    working_dir: /usr/src/rent-housing

    networks:
      - monorepo-network
    # for production
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  rent-housing-batch:
    container_name: rent-housing-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4006:3006
    volumes:
      - ./:/usr/src/rent-housing
    working_dir: /usr/src/rent-housing

    networks:
      - monorepo-network
    # for production
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# rentHousing: localhost: 4000 => container: 3000
# rentHousing-api: localhost: 4005 => container: 3005
# rent-housing-batch: localhost: 4006 => container: 3006

# docker compose up -d
# docker-compose start
# docker-compose stop
# docker-compose restart
# docker-compose stop && docker compose rm -f
